<?php

/**
 * @file
 * Contains module code.
 */

/**
 * Implements hook_help().
 */
function comment_reply_count_help($path, $arg) {
  switch ($path) {
    case 'admin/help#comment_reply_count':

      $filepath = dirname(__FILE__) . '/README.md';
      if (file_exists($filepath)) {
        $readme = file_get_contents($filepath);
      }
      if (!isset($readme)) {
        return NULL;
      }
      if (module_exists('markdown')) {
        $filters = module_invoke('markdown', 'filter_info');
        $info = $filters['filter_markdown'];
        if (function_exists($info['process callback'])) {
          $output = $info['process callback']($readme, NULL);
        }
        else {
          $output = '<pre>' . $readme . '</pre>';
        }
      }
      else {
        $output = '<pre>' . $readme . '</pre>';
      }

      return $output;
  }
}

/**
 * Implements hook_preprocess_comment().
 */
function comment_reply_count_preprocess_comment(&$variables) {
  // Added a jQuery file to toggle the indented replied.
  drupal_add_js(drupal_get_path('module', 'comment_reply_count') . '/js/comment_reply_count.js');
  // Added a CSS file to customize the Show/Hide Button.
  drupal_add_css(drupal_get_path('module', 'comment_reply_count') . '/css/comment_reply_count.css');

  $result = comment_reply_count_count($variables['id']);
  //dsm($result);
  // Only show the Reply count and Show/Hide
  // if the result fetch is not equals to zero.
  if ($result != 0) {
    $variables['content']['links']['comment']['#links']['comment-show'] = [
      'title' => t('<span>(@result) </span><span class="show-hide">Show</span>', ['@result' => $result]),
      'html' => TRUE,
    ];
  }
}

/**
 * Helper function to fetch Comment reply count.
 */
function comment_reply_count_count($cid) {
  $query = db_query('SELECT COUNT(*) FROM comment WHERE pid = :cid', array(':cid' => $cid));
  $result = $query->fetchField();
  return $result;
}
